### ISSUE TITLE
Copyright and license in the class files headers

### ISSUE THREAD

**Issue by xnike** [komamitsu/phi-accural-failure-detector#1]
Hi Mitsunori Komatsu,

We would very much like to use your fluency project and its dependency phi-accural-failure-detector as 3rd-party libraries, but we can't for the law reasons - a missing copyright and license header in the class files.
Could you please add them to a new minor release?

**Comment by komamitsu** [comment]
@xnike Added license header to source files at https://github.com/komamitsu/phi-accural-failure-detector/pull/2 and released them as 0.0.5

**Comment by xnike** [comment]
Thank you a lot
